name: Pipeline de Relatorio Diario

on:
    schedule:
        - cron: '00 20 * * *'
    workflow_dispatch:
jobs:
    executar-processamento:
        runs-on: ubuntu-latest
        
        steps:
            - name: Baixar o código do repositorio
              uses: actions/checkout@v3

            - name: Configurar o Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'
            
            - name: Instalar bibliotecas
              run: pip install pandas

            - name: Rodar o script de limpeza
              run: python banco.py         

            - name: Salvar o resultado (download)
              uses: actions/upload-artifact@v4
              with:
                name: relatorio-json
                path: relatorio.json